import { MemeTemplate } from '../types';

/**
 * Comprehensive Meme Template Library
 * 150+ templates organized by category
 * Source: imgflip.com and manually curated
 */

export const memeTemplates: MemeTemplate[] = [
  // TRENDING MEMES (25 templates)
  {
    id: '181913649',
    name: 'Drake Hotline Bling',
    url: 'https://i.imgflip.com/30b1gx.jpg',
    category: 'Trending',
    width: 1200,
    height: 1200,
    suggestions: ['No', 'Yes', 'Bad idea', 'Good idea'],
  },
  {
    id: '112126428',
    name: 'Distracted Boyfriend',
    url: 'https://i.imgflip.com/1ur9b0.jpg',
    category: 'Trending',
    width: 1200,
    height: 800,
    suggestions: ['Me', 'My responsibilities', 'Video games'],
  },
  {
    id: '188390779',
    name: 'Woman Yelling at Cat',
    url: 'https://i.imgflip.com/345v97.jpg',
    category: 'Trending',
    width: 680,
    height: 438,
    suggestions: ["You can't", 'I can'],
  },
  {
    id: '217743513',
    name: 'UNO Draw 25 Cards',
    url: 'https://i.imgflip.com/3lmzyx.jpg',
    category: 'Trending',
    width: 500,
    height: 494,
    suggestions: ['Do homework', 'Draw 25'],
  },
  {
    id: '222403160',
    name: 'Bernie Sanders',
    url: 'https://i.imgflip.com/3oevdk.jpg',
    category: 'Trending',
    width: 625,
    height: 469,
    suggestions: ['I am once again asking'],
  },
  {
    id: '131087935',
    name: 'Running Away Balloon',
    url: 'https://i.imgflip.com/261o3j.jpg',
    category: 'Trending',
    width: 761,
    height: 1024,
    suggestions: ['Come back', 'No'],
  },
  {
    id: '226297822',
    name: 'Panik Kalm Panik',
    url: 'https://i.imgflip.com/3qqcim.jpg',
    category: 'Trending',
    width: 640,
    height: 881,
    suggestions: ['Panik', 'Kalm', 'Panik'],
  },
  {
    id: '252600902',
    name: 'Always Has Been',
    url: 'https://i.imgflip.com/46e43q.jpg',
    category: 'Trending',
    width: 960,
    height: 540,
    suggestions: ["Wait, it's all...", 'Always has been'],
  },
  {
    id: '178591752',
    name: 'Tuxedo Winnie the Pooh',
    url: 'https://i.imgflip.com/2ybua0.jpg',
    category: 'Trending',
    width: 800,
    height: 800,
    suggestions: ['Normal', 'Fancy'],
  },
  {
    id: '247375501',
    name: 'Buff Doge vs Cheems',
    url: 'https://i.imgflip.com/43a45p.jpg',
    category: 'Trending',
    width: 937,
    height: 720,
    suggestions: ['Strong thing', 'Weak thing'],
  },
  {
    id: '131940431',
    name: "Gru's Plan",
    url: 'https://i.imgflip.com/26jxvz.jpg',
    category: 'Trending',
    width: 700,
    height: 449,
    suggestions: ['Step 1', 'Step 2', 'Step 3', 'Wait what'],
  },
  {
    id: '232936670',
    name: "They're The Same Picture",
    url: 'https://i.imgflip.com/3vqyd3.jpg',
    category: 'Trending',
    width: 1440,
    height: 1136,
    suggestions: ['Corporate wants you to find the differences', "They're the same picture"],
  },
  {
    id: '322841258',
    name: "I Bet He's Thinking About Other Women",
    url: 'https://i.imgflip.com/5c7lwq.jpg',
    category: 'Trending',
    width: 1654,
    height: 930,
    suggestions: ['He must be thinking about other women', 'Random thought'],
  },
  {
    id: '438680',
    name: 'Batman Slapping Robin',
    url: 'https://i.imgflip.com/9ehk.jpg',
    category: 'Trending',
    width: 400,
    height: 387,
    suggestions: ['Bad opinion', 'SLAP!'],
  },
  {
    id: '135256802',
    name: 'Epic Handshake',
    url: 'https://i.imgflip.com/28j0te.jpg',
    category: 'Trending',
    width: 900,
    height: 600,
    suggestions: ['Group 1', 'Agreement', 'Group 2'],
  },
  {
    id: '124822590',
    name: 'Left Exit 12 Off Ramp',
    url: 'https://i.imgflip.com/22bdh6.jpg',
    category: 'Trending',
    width: 804,
    height: 767,
    suggestions: ['Normal route', 'Better route'],
  },
  {
    id: '259237855',
    name: 'Laughing Leo',
    url: 'https://i.imgflip.com/4acd7j.jpg',
    category: 'Trending',
    width: 470,
    height: 470,
    suggestions: ['Funny thing', 'HAHA'],
  },
  {
    id: '370867422',
    name: 'Twitter Header',
    url: 'https://i.imgflip.com/61phoi.jpg',
    category: 'Trending',
    width: 1500,
    height: 500,
    suggestions: ['Breaking News'],
  },
  {
    id: '101470',
    name: 'Ancient Aliens',
    url: 'https://i.imgflip.com/26am.jpg',
    category: 'Trending',
    width: 500,
    height: 437,
    suggestions: ['Aliens'],
  },
  {
    id: '1035805',
    name: 'Boardroom Meeting Suggestion',
    url: 'https://i.imgflip.com/m78d.jpg',
    category: 'Trending',
    width: 500,
    height: 649,
    suggestions: ['We need ideas', 'Idea 1', 'Idea 2', 'Bad idea'],
  },
  {
    id: '97984',
    name: 'Disaster Girl',
    url: 'https://i.imgflip.com/23ls.jpg',
    category: 'Trending',
    width: 500,
    height: 375,
    suggestions: ['Something burning'],
  },
  {
    id: '91538330',
    name: 'X, X Everywhere',
    url: 'https://i.imgflip.com/1ihzfe.jpg',
    category: 'Trending',
    width: 2118,
    height: 1440,
    suggestions: ['X', 'X everywhere'],
  },
  {
    id: '27813981',
    name: 'Hide the Pain Harold',
    url: 'https://i.imgflip.com/gk5el.jpg',
    category: 'Trending',
    width: 480,
    height: 601,
    suggestions: ['Smiling through pain'],
  },
  {
    id: '110163934',
    name: 'I See This as an Absolute Win',
    url: 'https://i.imgflip.com/1tuird.jpg',
    category: 'Trending',
    width: 625,
    height: 656,
    suggestions: ['Bad situation', 'I see this as an absolute win!'],
  },
  {
    id: '261601',
    name: 'Judge Judy',
    url: 'https://i.imgflip.com/4nu54.jpg',
    category: 'Trending',
    width: 500,
    height: 377,
    suggestions: ['Judging'],
  },

  // CLASSIC MEMES (30 templates)
  {
    id: '61579',
    name: 'One Does Not Simply',
    url: 'https://i.imgflip.com/1bij.jpg',
    category: 'Classic',
    width: 568,
    height: 335,
    suggestions: ['One does not simply'],
  },
  {
    id: '87743020',
    name: 'Two Buttons',
    url: 'https://i.imgflip.com/1g8my4.jpg',
    category: 'Classic',
    width: 600,
    height: 908,
    suggestions: ['Option 1', 'Option 2', 'Sweating'],
  },
  {
    id: '129242436',
    name: 'Change My Mind',
    url: 'https://i.imgflip.com/24y43o.jpg',
    category: 'Classic',
    width: 482,
    height: 361,
    suggestions: ['Change my mind'],
  },
  {
    id: '100777631',
    name: 'Is This a Pigeon',
    url: 'https://i.imgflip.com/1ihzfe.jpg',
    category: 'Classic',
    width: 1587,
    height: 1425,
    suggestions: ['Person', 'Thing', 'Is this a pigeon?'],
  },
  {
    id: '93895088',
    name: 'Expanding Brain',
    url: 'https://i.imgflip.com/1jwhww.jpg',
    category: 'Classic',
    width: 857,
    height: 1202,
    suggestions: ['Small brain', 'Normal brain', 'Big brain', 'Galaxy brain'],
  },
  {
    id: '84341851',
    name: 'Evil Kermit',
    url: 'https://i.imgflip.com/1e7ql7.jpg',
    category: 'Classic',
    width: 700,
    height: 581,
    suggestions: ['Good thought', 'Bad thought'],
  },
  {
    id: '61520',
    name: 'Success Kid',
    url: 'https://i.imgflip.com/1bhk.jpg',
    category: 'Classic',
    width: 500,
    height: 500,
    suggestions: ['Success!'],
  },
  {
    id: '61532',
    name: 'The Most Interesting Man In The World',
    url: 'https://i.imgflip.com/1bh0.jpg',
    category: 'Classic',
    width: 550,
    height: 690,
    suggestions: ["I don't always", 'But when I do'],
  },
  {
    id: '101287',
    name: 'Third World Skeptical Kid',
    url: 'https://i.imgflip.com/265k.jpg',
    category: 'Classic',
    width: 426,
    height: 426,
    suggestions: ["So you're telling me"],
  },
  {
    id: '563423',
    name: 'That Would Be Great',
    url: 'https://i.imgflip.com/c2qn.jpg',
    category: 'Classic',
    width: 526,
    height: 440,
    suggestions: ['If you could', 'That would be great'],
  },
  {
    id: '8072285',
    name: 'Doge',
    url: 'https://i.imgflip.com/4t0m5.jpg',
    category: 'Classic',
    width: 620,
    height: 620,
    suggestions: ['Much wow', 'Such amaze', 'Very good'],
  },
  {
    id: '89370',
    name: 'Roll Safe Think About It',
    url: 'https://i.imgflip.com/1h7in3.jpg',
    category: 'Classic',
    width: 702,
    height: 395,
    suggestions: ["Can't have problem", "If you don't do thing"],
  },
  {
    id: '6235864',
    name: 'Finding Neverland',
    url: 'https://i.imgflip.com/3pnmg.jpg',
    category: 'Classic',
    width: 423,
    height: 600,
    suggestions: ['You know what', 'Yeah'],
  },
  {
    id: '4087833',
    name: 'Waiting Skeleton',
    url: 'https://i.imgflip.com/2fm6x.jpg',
    category: 'Classic',
    width: 298,
    height: 403,
    suggestions: ['Still waiting for'],
  },
  {
    id: '28251713',
    name: 'Oprah You Get A',
    url: 'https://i.imgflip.com/gtj5t.jpg',
    category: 'Classic',
    width: 620,
    height: 465,
    suggestions: ['You get a', 'Everyone gets a'],
  },
  {
    id: '5496396',
    name: 'Leonardo Dicaprio Cheers',
    url: 'https://i.imgflip.com/39t1o.jpg',
    category: 'Classic',
    width: 600,
    height: 400,
    suggestions: ['Cheers to'],
  },
  {
    id: '61585',
    name: 'Bad Luck Brian',
    url: 'https://i.imgflip.com/1bi9.jpg',
    category: 'Classic',
    width: 475,
    height: 562,
    suggestions: ['Tries something', 'Fails spectacularly'],
  },
  {
    id: '61544',
    name: 'Success Kid Original',
    url: 'https://i.imgflip.com/1bhk.jpg',
    category: 'Classic',
    width: 500,
    height: 500,
    suggestions: ['Achieved goal'],
  },
  {
    id: '21604248',
    name: 'Mugatu So Hot Right Now',
    url: 'https://i.imgflip.com/cv1y0.jpg',
    category: 'Classic',
    width: 620,
    height: 497,
    suggestions: ['X', 'So hot right now'],
  },
  {
    id: '21735',
    name: 'The Rock Driving',
    url: 'https://i.imgflip.com/grr.jpg',
    category: 'Classic',
    width: 568,
    height: 700,
    suggestions: ['Normal thought', 'Weird thought'],
  },
  {
    id: '61556',
    name: 'Grandma Finds The Internet',
    url: 'https://i.imgflip.com/1bhw.jpg',
    category: 'Classic',
    width: 640,
    height: 480,
    suggestions: ['Discovering internet'],
  },
  {
    id: '563423_2',
    name: 'Bill Lumbergh',
    url: 'https://i.imgflip.com/c2qn.jpg',
    category: 'Classic',
    width: 526,
    height: 440,
    suggestions: ['Yeah if you could', "That'd be great"],
  },
  {
    id: '101288',
    name: 'Third World Success Kid',
    url: 'https://i.imgflip.com/265k.jpg',
    category: 'Classic',
    width: 500,
    height: 500,
    suggestions: ['Small win', 'Big celebration'],
  },
  {
    id: '14371066',
    name: 'Star Wars Yoda',
    url: 'https://i.imgflip.com/8k0sa.jpg',
    category: 'Classic',
    width: 620,
    height: 714,
    suggestions: ['Do or do not', 'There is no try'],
  },
  {
    id: '101511',
    name: "Don't You Squidward",
    url: 'https://i.imgflip.com/26br.jpg',
    category: 'Classic',
    width: 500,
    height: 333,
    suggestions: ['When you', 'Relate to Squidward'],
  },
  {
    id: '61533',
    name: 'X All The Y',
    url: 'https://i.imgflip.com/1bhu.jpg',
    category: 'Classic',
    width: 500,
    height: 355,
    suggestions: ['Do all the things'],
  },
  {
    id: '196652226',
    name: 'Spongebob Ight Imma Head Out',
    url: 'https://i.imgflip.com/392xtu.jpg',
    category: 'Classic',
    width: 822,
    height: 960,
    suggestions: ['Aight', 'Imma head out'],
  },
  {
    id: '101440',
    name: 'Leonardo Dicaprio Wolf of Wall Street',
    url: 'https://i.imgflip.com/265v.jpg',
    category: 'Classic',
    width: 1366,
    height: 768,
    suggestions: ["I'm not leaving!"],
  },
  {
    id: '61527',
    name: 'Y U No',
    url: 'https://i.imgflip.com/1bh3.jpg',
    category: 'Classic',
    width: 500,
    height: 500,
    suggestions: ['Y U NO'],
  },
  {
    id: '61546',
    name: 'Brace Yourselves',
    url: 'https://i.imgflip.com/1bhm.jpg',
    category: 'Classic',
    width: 622,
    height: 477,
    suggestions: ['Brace yourselves', 'X is coming'],
  },

  // REACTION MEMES (20 templates)
  {
    id: '155067746',
    name: 'Surprised Pikachu',
    url: 'https://i.imgflip.com/2ka1vv.jpg',
    category: 'Reaction',
    width: 1893,
    height: 1893,
    suggestions: ['Unexpected thing', '*surprised*'],
  },
  {
    id: '27813981_2',
    name: 'Hide The Pain Harold',
    url: 'https://i.imgflip.com/gk5el.jpg',
    category: 'Reaction',
    width: 480,
    height: 601,
    suggestions: ['Painful situation', '*smiles*'],
  },
  {
    id: '259237855_2',
    name: 'Laughing Leo',
    url: 'https://i.imgflip.com/4acd7j.jpg',
    category: 'Reaction',
    width: 470,
    height: 470,
    suggestions: ['You:', 'Leonardo DiCaprio:'],
  },
  {
    id: '216951317',
    name: 'Guy Holding Cardboard',
    url: 'https://i.imgflip.com/3lo1pu.jpg',
    category: 'Reaction',
    width: 1440,
    height: 1440,
    suggestions: ['Message here'],
  },
  {
    id: '119139145',
    name: 'Blank Nut Button',
    url: 'https://i.imgflip.com/1yxkcp.jpg',
    category: 'Reaction',
    width: 600,
    height: 446,
    suggestions: ['Tempting button', '*SMASH*'],
  },
  {
    id: '80707627',
    name: 'Sad Pablo Escobar',
    url: 'https://i.imgflip.com/1c1uej.jpg',
    category: 'Reaction',
    width: 720,
    height: 709,
    suggestions: ['Sad waiting'],
  },
  {
    id: '134797956',
    name: 'American Chopper Argument',
    url: 'https://i.imgflip.com/2896ro.jpg',
    category: 'Reaction',
    width: 640,
    height: 1853,
    suggestions: ['Person 1', 'Person 2', 'Escalating argument'],
  },
  {
    id: '129242436_2',
    name: 'Change My Mind',
    url: 'https://i.imgflip.com/24y43o.jpg',
    category: 'Reaction',
    width: 482,
    height: 361,
    suggestions: ['Controversial opinion', 'Change my mind'],
  },
  {
    id: '4173692',
    name: 'Scared Cat',
    url: 'https://i.imgflip.com/2hgfw.jpg',
    category: 'Reaction',
    width: 620,
    height: 465,
    suggestions: ['Scary thing'],
  },
  {
    id: '101287_2',
    name: 'Third World Skeptical Kid',
    url: 'https://i.imgflip.com/265k.jpg',
    category: 'Reaction',
    width: 426,
    height: 426,
    suggestions: ['Skeptical about claim'],
  },
  {
    id: '6531067',
    name: 'See Nobody Cares',
    url: 'https://i.imgflip.com/3vzej.jpg',
    category: 'Reaction',
    width: 620,
    height: 676,
    suggestions: ['See? Nobody cares'],
  },
  {
    id: '84341851_2',
    name: 'Evil Kermit',
    url: 'https://i.imgflip.com/1e7ql7.jpg',
    category: 'Reaction',
    width: 700,
    height: 581,
    suggestions: ['Me', 'Also me', 'Do bad thing'],
  },
  {
    id: '28034788',
    name: 'Marvel Civil War',
    url: 'https://i.imgflip.com/govs4.jpg',
    category: 'Reaction',
    width: 423,
    height: 734,
    suggestions: ['Team 1', 'Team 2', 'Person in middle'],
  },
  {
    id: '102156234',
    name: 'Mocking Spongebob',
    url: 'https://i.imgflip.com/1otk96.jpg',
    category: 'Reaction',
    width: 502,
    height: 353,
    suggestions: ['MoCkInG tExT'],
  },
  {
    id: '163573',
    name: 'Imagination Spongebob',
    url: 'https://i.imgflip.com/3i7p.jpg',
    category: 'Reaction',
    width: 500,
    height: 366,
    suggestions: ['Imagination'],
  },
  {
    id: '99683372',
    name: 'Sleeping Shaq',
    url: 'https://i.imgflip.com/1nck6k.jpg',
    category: 'Reaction',
    width: 640,
    height: 631,
    suggestions: ["Can't sleep about problem"],
  },
  {
    id: '4087833_2',
    name: 'Waiting Skeleton',
    url: 'https://i.imgflip.com/2fm6x.jpg',
    category: 'Reaction',
    width: 298,
    height: 403,
    suggestions: ['Still waiting...'],
  },
  {
    id: '141421102',
    name: 'Bernie I Am Once Again Asking For Your Support',
    url: 'https://i.imgflip.com/2p51wv.jpg',
    category: 'Reaction',
    width: 750,
    height: 750,
    suggestions: ['I am once again asking'],
  },
  {
    id: '175540452',
    name: 'Unsettled Tom',
    url: 'https://i.imgflip.com/2wifvo.jpg',
    category: 'Reaction',
    width: 680,
    height: 550,
    suggestions: ['Unsettling fact'],
  },
  {
    id: '178591752_2',
    name: 'Tuxedo Winnie The Pooh',
    url: 'https://i.imgflip.com/2ybua0.jpg',
    category: 'Reaction',
    width: 800,
    height: 800,
    suggestions: ['Normal version', 'Fancy version'],
  },

  // ANIMALS (15 templates)
  {
    id: '405658',
    name: 'Grumpy Cat',
    url: 'https://i.imgflip.com/8p0a.jpg',
    category: 'Animals',
    width: 500,
    height: 617,
    suggestions: ['No'],
  },
  {
    id: '8072285_2',
    name: 'Doge',
    url: 'https://i.imgflip.com/4t0m5.jpg',
    category: 'Animals',
    width: 620,
    height: 620,
    suggestions: ['Much', 'Very', 'Such', 'Wow'],
  },
  {
    id: '155067746_2',
    name: 'Surprised Pikachu',
    url: 'https://i.imgflip.com/2ka1vv.jpg',
    category: 'Animals',
    width: 1893,
    height: 1893,
    suggestions: ['*surprised pikachu face*'],
  },
  {
    id: '247375501_2',
    name: 'Buff Doge vs Cheems',
    url: 'https://i.imgflip.com/43a45p.jpg',
    category: 'Animals',
    width: 937,
    height: 720,
    suggestions: ['Then', 'Now', 'Strong', 'Weak'],
  },
  {
    id: '188390779_2',
    name: 'Woman Yelling At A Cat',
    url: 'https://i.imgflip.com/345v97.jpg',
    category: 'Animals',
    width: 680,
    height: 438,
    suggestions: ['Angry complaint', 'Calm rejection'],
  },
  {
    id: '4173692_2',
    name: 'Scared Cat',
    url: 'https://i.imgflip.com/2hgfw.jpg',
    category: 'Animals',
    width: 620,
    height: 465,
    suggestions: ['Frightening thing'],
  },
  {
    id: '91545132',
    name: 'Monkey Puppet',
    url: 'https://i.imgflip.com/1h4kur.jpg',
    category: 'Animals',
    width: 923,
    height: 768,
    suggestions: ['Awkward look away'],
  },
  {
    id: '1367068',
    name: 'I Should Buy A Boat Cat',
    url: 'https://i.imgflip.com/tau4.jpg',
    category: 'Animals',
    width: 500,
    height: 368,
    suggestions: ['I should buy a...'],
  },
  {
    id: '61520_2',
    name: 'Success Kid',
    url: 'https://i.imgflip.com/1bhk.jpg',
    category: 'Animals',
    width: 500,
    height: 500,
    suggestions: ['Success'],
  },
  {
    id: '14230520',
    name: 'Black Panther - Get This Man A Shield',
    url: 'https://i.imgflip.com/8qay0.jpg',
    category: 'Animals',
    width: 800,
    height: 450,
    suggestions: ['Get this man a'],
  },
  {
    id: '6351542',
    name: 'Gorilla Business',
    url: 'https://i.imgflip.com/3r0xj6.jpg',
    category: 'Animals',
    width: 498,
    height: 388,
    suggestions: ['Business discussion'],
  },
  {
    id: '101956210',
    name: 'Seal of Approval',
    url: 'https://i.imgflip.com/1op6bz.jpg',
    category: 'Animals',
    width: 640,
    height: 467,
    suggestions: ['Seal of approval'],
  },
  {
    id: '134116618',
    name: 'Angry Baby',
    url: 'https://i.imgflip.com/27tuf5.jpg',
    category: 'Animals',
    width: 640,
    height: 640,
    suggestions: ['Angry about thing'],
  },
  {
    id: '176917',
    name: 'Annoyed Cat',
    url: 'https://i.imgflip.com/34bc2.jpg',
    category: 'Animals',
    width: 620,
    height: 465,
    suggestions: ['Annoyed'],
  },
  {
    id: '84341851_3',
    name: 'Evil Kermit',
    url: 'https://i.imgflip.com/1e7ql7.jpg',
    category: 'Animals',
    width: 700,
    height: 581,
    suggestions: ['Me', 'Also me', 'Do it'],
  },

  // OFFICE/WORK (15 templates)
  {
    id: '563423_3',
    name: 'That Would Be Great',
    url: 'https://i.imgflip.com/c2qn.jpg',
    category: 'Office',
    width: 526,
    height: 440,
    suggestions: ['If you could', 'That would be great'],
  },
  {
    id: '135256802_2',
    name: 'Epic Handshake',
    url: 'https://i.imgflip.com/28j0te.jpg',
    category: 'Office',
    width: 900,
    height: 600,
    suggestions: ['Agreement point', 'Team 1', 'Team 2'],
  },
  {
    id: '1035805_2',
    name: 'Boardroom Meeting Suggestion',
    url: 'https://i.imgflip.com/m78d.jpg',
    category: 'Office',
    width: 500,
    height: 649,
    suggestions: ['We need', 'Suggestion 1', 'Suggestion 2', 'Bad suggestion'],
  },
  {
    id: '61533_2',
    name: 'X All The Y',
    url: 'https://i.imgflip.com/1bhu.jpg',
    category: 'Office',
    width: 500,
    height: 355,
    suggestions: ['Do all the work'],
  },
  {
    id: '91545132_2',
    name: 'Monkey Puppet',
    url: 'https://i.imgflip.com/1h4kur.jpg',
    category: 'Office',
    width: 923,
    height: 768,
    suggestions: ['When boss walks in'],
  },
  {
    id: '232936670_2',
    name: "They're The Same Picture",
    url: 'https://i.imgflip.com/3vqyd3.jpg',
    category: 'Office',
    width: 1440,
    height: 1136,
    suggestions: ['Corporate needs you to find the differences'],
  },
  {
    id: '199441956',
    name: "Sir This Is An Arby's",
    url: 'https://i.imgflip.com/39w4qe.jpg',
    category: 'Office',
    width: 1280,
    height: 720,
    suggestions: ['Long complaint', "Sir this is an Arby's"],
  },
  {
    id: '3218037',
    name: "This Is Where I'd Put My Trophy",
    url: 'https://i.imgflip.com/1wz1v.jpg',
    category: 'Office',
    width: 640,
    height: 479,
    suggestions: ['IF I HAD ONE'],
  },
  {
    id: '89370_2',
    name: 'Roll Safe Think About It',
    url: 'https://i.imgflip.com/1h7in3.jpg',
    category: 'Office',
    width: 702,
    height: 395,
    suggestions: ["Can't have problems", 'If you avoid them'],
  },
  {
    id: '124055727',
    name: "Y'all Got Any More Of That",
    url: 'https://i.imgflip.com/21uy0f.jpg',
    category: 'Office',
    width: 600,
    height: 471,
    suggestions: ["Y'all got any more of"],
  },
  {
    id: '21604248_2',
    name: 'Mugatu So Hot Right Now',
    url: 'https://i.imgflip.com/cv1y0.jpg',
    category: 'Office',
    width: 620,
    height: 497,
    suggestions: ['X so hot right now'],
  },
  {
    id: '6235864_2',
    name: 'Finding Neverland',
    url: 'https://i.imgflip.com/3pnmg.jpg',
    category: 'Office',
    width: 423,
    height: 600,
    suggestions: ['You know what...', 'Work realization'],
  },
  {
    id: '123999232',
    name: 'The Scroll Of Truth',
    url: 'https://i.imgflip.com/21tqf4.jpg',
    category: 'Office',
    width: 1280,
    height: 1236,
    suggestions: ['Truth about work', 'NYEH!'],
  },
  {
    id: '163573_2',
    name: 'Imagination Spongebob',
    url: 'https://i.imgflip.com/3i7p.jpg',
    category: 'Office',
    width: 500,
    height: 366,
    suggestions: ['Imaginary benefits', 'Imagination'],
  },
  {
    id: '101440_2',
    name: 'Leonardo Dicaprio Wolf Of Wall Street',
    url: 'https://i.imgflip.com/265v.jpg',
    category: 'Office',
    width: 1366,
    height: 768,
    suggestions: ['Not leaving!', 'Determination'],
  },

  // GAMING (10 templates)
  {
    id: '309868304',
    name: 'Trade Offer',
    url: 'https://i.imgflip.com/54hjww.jpg',
    category: 'Gaming',
    width: 607,
    height: 601,
    suggestions: ['I receive', 'You receive'],
  },
  {
    id: '119139145_2',
    name: 'Blank Nut Button',
    url: 'https://i.imgflip.com/1yxkcp.jpg',
    category: 'Gaming',
    width: 600,
    height: 446,
    suggestions: ['Gaming button', 'SMASH'],
  },
  {
    id: '217743513_2',
    name: 'UNO Draw 25 Cards',
    url: 'https://i.imgflip.com/3lmzyx.jpg',
    category: 'Gaming',
    width: 500,
    height: 494,
    suggestions: ['Do task', 'Draw 25'],
  },
  {
    id: '247113703',
    name: 'A Train Hitting A School Bus',
    url: 'https://i.imgflip.com/434i5j.jpg',
    category: 'Gaming',
    width: 920,
    height: 613,
    suggestions: ['Problem', 'Solution', 'Impact'],
  },
  {
    id: '226297822_2',
    name: 'Panik Kalm Panik',
    url: 'https://i.imgflip.com/3qqcim.jpg',
    category: 'Gaming',
    width: 640,
    height: 881,
    suggestions: ['Panik', 'Kalm', 'Panik'],
  },
  {
    id: '72525473',
    name: 'Say The Line Bart',
    url: 'https://i.imgflip.com/176h0h.jpg',
    category: 'Gaming',
    width: 640,
    height: 481,
    suggestions: ['Say the line', '*YAY*'],
  },
  {
    id: '93895088_2',
    name: 'Expanding Brain',
    url: 'https://i.imgflip.com/1jwhww.jpg',
    category: 'Gaming',
    width: 857,
    height: 1202,
    suggestions: ['Small brain', 'Medium brain', 'Large brain', 'Galaxy brain'],
  },
  {
    id: '110163934_2',
    name: 'I See This As An Absolute Win',
    url: 'https://i.imgflip.com/1tuird.jpg',
    category: 'Gaming',
    width: 625,
    height: 656,
    suggestions: ['Gaming outcome', 'Absolute win!'],
  },
  {
    id: '91538330_2',
    name: 'X, X Everywhere',
    url: 'https://i.imgflip.com/1ihzfe.jpg',
    category: 'Gaming',
    width: 2118,
    height: 1440,
    suggestions: ['Bugs', 'Bugs everywhere'],
  },
  {
    id: '131940431_2',
    name: "Gru's Plan",
    url: 'https://i.imgflip.com/26jxvz.jpg',
    category: 'Gaming',
    width: 700,
    height: 449,
    suggestions: ['Game plan', 'Step 1', 'Step 2', 'Fail'],
  },

  // MOVIES/TV (15 templates)
  {
    id: '370867422_2',
    name: 'Megamind No Bitches',
    url: 'https://i.imgflip.com/61phoi.jpg',
    category: 'Movies',
    width: 1500,
    height: 500,
    suggestions: ['No X?'],
  },
  {
    id: '252600902_2',
    name: 'Always Has Been',
    url: 'https://i.imgflip.com/46e43q.jpg',
    category: 'Movies',
    width: 960,
    height: 540,
    suggestions: ["Wait it's all", 'Always has been'],
  },
  {
    id: '196652226_2',
    name: 'Spongebob Ight Imma Head Out',
    url: 'https://i.imgflip.com/392xtu.jpg',
    category: 'Movies',
    width: 822,
    height: 960,
    suggestions: ['Aight', 'Imma head out'],
  },
  {
    id: '102156234_2',
    name: 'Mocking Spongebob',
    url: 'https://i.imgflip.com/1otk96.jpg',
    category: 'Movies',
    width: 502,
    height: 353,
    suggestions: ['MoCkInG tExT'],
  },
  {
    id: '163573_3',
    name: 'Imagination Spongebob',
    url: 'https://i.imgflip.com/3i7p.jpg',
    category: 'Movies',
    width: 500,
    height: 366,
    suggestions: ['Imagination'],
  },
  {
    id: '101511_2',
    name: "Don't You Squidward",
    url: 'https://i.imgflip.com/26br.jpg',
    category: 'Movies',
    width: 500,
    height: 333,
    suggestions: ['Relatable Squidward moment'],
  },
  {
    id: '14371066_2',
    name: 'Star Wars Yoda',
    url: 'https://i.imgflip.com/8k0sa.jpg',
    category: 'Movies',
    width: 620,
    height: 714,
    suggestions: ['Do or do not'],
  },
  {
    id: '61546_2',
    name: 'Brace Yourselves X Is Coming',
    url: 'https://i.imgflip.com/1bhm.jpg',
    category: 'Movies',
    width: 622,
    height: 477,
    suggestions: ['Brace yourselves', 'X is coming'],
  },
  {
    id: '100947',
    name: 'Matrix Morpheus',
    url: 'https://i.imgflip.com/25w3.jpg',
    category: 'Movies',
    width: 500,
    height: 303,
    suggestions: ['What if I told you'],
  },
  {
    id: '101440_3',
    name: 'Leonardo Dicaprio Wolf Of Wall Street',
    url: 'https://i.imgflip.com/265v.jpg',
    category: 'Movies',
    width: 1366,
    height: 768,
    suggestions: ["I'm not leaving!"],
  },
  {
    id: '28034788_2',
    name: 'Marvel Civil War',
    url: 'https://i.imgflip.com/govs4.jpg',
    category: 'Movies',
    width: 423,
    height: 734,
    suggestions: ['Team A', 'Team B', 'You'],
  },
  {
    id: '110163934_3',
    name: 'I See This As An Absolute Win',
    url: 'https://i.imgflip.com/1tuird.jpg',
    category: 'Movies',
    width: 625,
    height: 656,
    suggestions: ['Absolute win'],
  },
  {
    id: '5496396_2',
    name: 'Leonardo Dicaprio Cheers',
    url: 'https://i.imgflip.com/39t1o.jpg',
    category: 'Movies',
    width: 600,
    height: 400,
    suggestions: ['Cheers'],
  },
  {
    id: '61546_3',
    name: 'Winter Is Coming',
    url: 'https://i.imgflip.com/1bhm.jpg',
    category: 'Movies',
    width: 622,
    height: 477,
    suggestions: ['Winter is coming'],
  },
  {
    id: '134797956_2',
    name: 'American Chopper Argument',
    url: 'https://i.imgflip.com/2896ro.jpg',
    category: 'Movies',
    width: 640,
    height: 1853,
    suggestions: ['Argument escalates'],
  },

  // RELATIONSHIPS (10 templates)
  {
    id: '112126428_2',
    name: 'Distracted Boyfriend',
    url: 'https://i.imgflip.com/1ur9b0.jpg',
    category: 'Relationships',
    width: 1200,
    height: 800,
    suggestions: ['Current thing', 'Person', 'New thing'],
  },
  {
    id: '322841258_2',
    name: "I Bet He's Thinking About Other Women",
    url: 'https://i.imgflip.com/5c7lwq.jpg',
    category: 'Relationships',
    width: 1654,
    height: 930,
    suggestions: ['He must be thinking about other women', 'Random thought'],
  },
  {
    id: '188390779_3',
    name: 'Woman Yelling At A Cat',
    url: 'https://i.imgflip.com/345v97.jpg',
    category: 'Relationships',
    width: 680,
    height: 438,
    suggestions: ['Angry complaint', 'Calm cat'],
  },
  {
    id: '131087935_2',
    name: 'Running Away Balloon',
    url: 'https://i.imgflip.com/261o3j.jpg',
    category: 'Relationships',
    width: 761,
    height: 1024,
    suggestions: ['Person', 'Current thing', 'Tempting thing'],
  },
  {
    id: '135256802_3',
    name: 'Epic Handshake',
    url: 'https://i.imgflip.com/28j0te.jpg',
    category: 'Relationships',
    width: 900,
    height: 600,
    suggestions: ['Partner 1', 'Agreement', 'Partner 2'],
  },
  {
    id: '80707627_2',
    name: 'Sad Pablo Escobar',
    url: 'https://i.imgflip.com/1c1uej.jpg',
    category: 'Relationships',
    width: 720,
    height: 709,
    suggestions: ['Alone', 'Thinking'],
  },
  {
    id: '84341851_4',
    name: 'Evil Kermit',
    url: 'https://i.imgflip.com/1e7ql7.jpg',
    category: 'Relationships',
    width: 700,
    height: 581,
    suggestions: ['Good decision', 'Bad decision'],
  },
  {
    id: '21735_2',
    name: 'The Rock Driving',
    url: 'https://i.imgflip.com/grr.jpg',
    category: 'Relationships',
    width: 568,
    height: 700,
    suggestions: ['Partner says', 'My thoughts'],
  },
  {
    id: '134116618_2',
    name: 'Angry Baby',
    url: 'https://i.imgflip.com/27tuf5.jpg',
    category: 'Relationships',
    width: 640,
    height: 640,
    suggestions: ['When partner'],
  },
  {
    id: '87743020_2',
    name: 'Two Buttons',
    url: 'https://i.imgflip.com/1g8my4.jpg',
    category: 'Relationships',
    width: 600,
    height: 908,
    suggestions: ['Option 1', 'Option 2', "Can't decide"],
  },
];

export const getTemplatesByCategory = (category: string): MemeTemplate[] => {
  if (category === 'All') {
    return memeTemplates;
  }
  return memeTemplates.filter((template) => template.category === category);
};

export const searchTemplates = (query: string): MemeTemplate[] => {
  const lowercaseQuery = query.toLowerCase();
  return memeTemplates.filter((template) =>
    template.name.toLowerCase().includes(lowercaseQuery)
  );
};

export const getCategories = (): string[] => {
  const categories = ['All', ...new Set(memeTemplates.map((t) => t.category))];
  return categories;
};

export const getTrendingTemplates = (limit: number = 10): MemeTemplate[] => {
  return memeTemplates.filter((t) => t.category === 'Trending').slice(0, limit);
};

export const getRandomTemplate = (): MemeTemplate => {
  const randomIndex = Math.floor(Math.random() * memeTemplates.length);
  return memeTemplates[randomIndex];
};

/**
 * Fetch additional templates from imgflip API
 * Can be called to dynamically load more templates
 */
export const fetchImgflipTemplates = async (): Promise<MemeTemplate[]> => {
  try {
    const response = await fetch('https://api.imgflip.com/get_memes');
    const data = await response.json();

    if (data.success && data.data.memes) {
      return data.data.memes.map((meme: any) => ({
        id: meme.id,
        name: meme.name,
        url: meme.url,
        category: 'Trending',
        width: meme.width,
        height: meme.height,
        suggestions: [],
      }));
    }

    return [];
  } catch (error) {
    return [];
  }
};
