/**
 * Sticker Library - Free Emojis
 * Using Unicode emojis (100% free, no API needed)
 * Organized by category for easy browsing
 */

export interface Sticker {
  id: string;
  emoji: string;
  name: string;
  category: string;
}

export const STICKER_CATEGORIES = [
  'Faces',
  'Gestures',
  'Animals',
  'Food',
  'Activities',
  'Objects',
  'Symbols',
  'Popular',
];

export const stickers: Sticker[] = [
  // Popular (Most Used)
  { id: 'pop_1', emoji: '😂', name: 'Laughing', category: 'Popular' },
  { id: 'pop_2', emoji: '💀', name: 'Skull', category: 'Popular' },
  { id: 'pop_3', emoji: '🔥', name: 'Fire', category: 'Popular' },
  { id: 'pop_4', emoji: '💯', name: '100', category: 'Popular' },
  { id: 'pop_5', emoji: '👀', name: 'Eyes', category: 'Popular' },
  { id: 'pop_6', emoji: '🤣', name: 'ROFL', category: 'Popular' },
  { id: 'pop_7', emoji: '❤️', name: 'Heart', category: 'Popular' },
  { id: 'pop_8', emoji: '💩', name: 'Poop', category: 'Popular' },
  { id: 'pop_9', emoji: '🤡', name: 'Clown', category: 'Popular' },
  { id: 'pop_10', emoji: '💪', name: 'Strong', category: 'Popular' },
  { id: 'pop_11', emoji: '🧢', name: 'Cap', category: 'Popular' },
  { id: 'pop_12', emoji: '🤝', name: 'Handshake', category: 'Popular' },

  // Faces & Expressions
  { id: 'face_1', emoji: '😀', name: 'Grin', category: 'Faces' },
  { id: 'face_2', emoji: '😃', name: 'Big Smile', category: 'Faces' },
  { id: 'face_3', emoji: '😄', name: 'Happy', category: 'Faces' },
  { id: 'face_4', emoji: '😁', name: 'Beaming', category: 'Faces' },
  { id: 'face_5', emoji: '😆', name: 'Laughing', category: 'Faces' },
  { id: 'face_6', emoji: '😅', name: 'Sweat Smile', category: 'Faces' },
  { id: 'face_7', emoji: '🤣', name: 'ROFL', category: 'Faces' },
  { id: 'face_8', emoji: '😂', name: 'Joy', category: 'Faces' },
  { id: 'face_9', emoji: '🙂', name: 'Slight Smile', category: 'Faces' },
  { id: 'face_10', emoji: '🙃', name: 'Upside Down', category: 'Faces' },
  { id: 'face_11', emoji: '😉', name: 'Wink', category: 'Faces' },
  { id: 'face_12', emoji: '😊', name: 'Blush', category: 'Faces' },
  { id: 'face_13', emoji: '😇', name: 'Angel', category: 'Faces' },
  { id: 'face_14', emoji: '🥰', name: 'Love', category: 'Faces' },
  { id: 'face_15', emoji: '😍', name: 'Heart Eyes', category: 'Faces' },
  { id: 'face_16', emoji: '🤩', name: 'Star Eyes', category: 'Faces' },
  { id: 'face_17', emoji: '😘', name: 'Kiss', category: 'Faces' },
  { id: 'face_18', emoji: '😗', name: 'Kissing', category: 'Faces' },
  { id: 'face_19', emoji: '😚', name: 'Kiss Closed', category: 'Faces' },
  { id: 'face_20', emoji: '😙', name: 'Kiss Smile', category: 'Faces' },
  { id: 'face_21', emoji: '😋', name: 'Yum', category: 'Faces' },
  { id: 'face_22', emoji: '😛', name: 'Tongue', category: 'Faces' },
  { id: 'face_23', emoji: '😜', name: 'Wink Tongue', category: 'Faces' },
  { id: 'face_24', emoji: '🤪', name: 'Zany', category: 'Faces' },
  { id: 'face_25', emoji: '😝', name: 'Squint Tongue', category: 'Faces' },
  { id: 'face_26', emoji: '🤑', name: 'Money', category: 'Faces' },
  { id: 'face_27', emoji: '🤗', name: 'Hug', category: 'Faces' },
  { id: 'face_28', emoji: '🤭', name: 'Hand Over', category: 'Faces' },
  { id: 'face_29', emoji: '🤫', name: 'Shh', category: 'Faces' },
  { id: 'face_30', emoji: '🤔', name: 'Thinking', category: 'Faces' },
  { id: 'face_31', emoji: '🤐', name: 'Zipper', category: 'Faces' },
  { id: 'face_32', emoji: '🤨', name: 'Raised Eyebrow', category: 'Faces' },
  { id: 'face_33', emoji: '😐', name: 'Neutral', category: 'Faces' },
  { id: 'face_34', emoji: '😑', name: 'Expressionless', category: 'Faces' },
  { id: 'face_35', emoji: '😶', name: 'No Mouth', category: 'Faces' },
  { id: 'face_36', emoji: '😏', name: 'Smirk', category: 'Faces' },
  { id: 'face_37', emoji: '😒', name: 'Unamused', category: 'Faces' },
  { id: 'face_38', emoji: '🙄', name: 'Eye Roll', category: 'Faces' },
  { id: 'face_39', emoji: '😬', name: 'Grimace', category: 'Faces' },
  { id: 'face_40', emoji: '🤥', name: 'Lying', category: 'Faces' },
  { id: 'face_41', emoji: '😌', name: 'Relieved', category: 'Faces' },
  { id: 'face_42', emoji: '😔', name: 'Pensive', category: 'Faces' },
  { id: 'face_43', emoji: '😪', name: 'Sleepy', category: 'Faces' },
  { id: 'face_44', emoji: '🤤', name: 'Drool', category: 'Faces' },
  { id: 'face_45', emoji: '😴', name: 'Sleeping', category: 'Faces' },
  { id: 'face_46', emoji: '😷', name: 'Mask', category: 'Faces' },
  { id: 'face_47', emoji: '🤒', name: 'Sick', category: 'Faces' },
  { id: 'face_48', emoji: '🤕', name: 'Injured', category: 'Faces' },
  { id: 'face_49', emoji: '🤢', name: 'Nauseated', category: 'Faces' },
  { id: 'face_50', emoji: '🤮', name: 'Vomit', category: 'Faces' },
  { id: 'face_51', emoji: '🤧', name: 'Sneeze', category: 'Faces' },
  { id: 'face_52', emoji: '🥵', name: 'Hot', category: 'Faces' },
  { id: 'face_53', emoji: '🥶', name: 'Cold', category: 'Faces' },
  { id: 'face_54', emoji: '😵', name: 'Dizzy', category: 'Faces' },
  { id: 'face_55', emoji: '🤯', name: 'Mind Blown', category: 'Faces' },
  { id: 'face_56', emoji: '🤠', name: 'Cowboy', category: 'Faces' },
  { id: 'face_57', emoji: '🥳', name: 'Party', category: 'Faces' },
  { id: 'face_58', emoji: '😎', name: 'Cool', category: 'Faces' },
  { id: 'face_59', emoji: '🤓', name: 'Nerd', category: 'Faces' },
  { id: 'face_60', emoji: '🧐', name: 'Monocle', category: 'Faces' },
  { id: 'face_61', emoji: '😕', name: 'Confused', category: 'Faces' },
  { id: 'face_62', emoji: '😟', name: 'Worried', category: 'Faces' },
  { id: 'face_63', emoji: '🙁', name: 'Frown', category: 'Faces' },
  { id: 'face_64', emoji: '😮', name: 'Wow', category: 'Faces' },
  { id: 'face_65', emoji: '😯', name: 'Hushed', category: 'Faces' },
  { id: 'face_66', emoji: '😲', name: 'Astonished', category: 'Faces' },
  { id: 'face_67', emoji: '😳', name: 'Flushed', category: 'Faces' },
  { id: 'face_68', emoji: '🥺', name: 'Pleading', category: 'Faces' },
  { id: 'face_69', emoji: '😦', name: 'Frowning', category: 'Faces' },
  { id: 'face_70', emoji: '😧', name: 'Anguished', category: 'Faces' },
  { id: 'face_71', emoji: '😨', name: 'Fearful', category: 'Faces' },
  { id: 'face_72', emoji: '😰', name: 'Anxious', category: 'Faces' },
  { id: 'face_73', emoji: '😥', name: 'Sad', category: 'Faces' },
  { id: 'face_74', emoji: '😢', name: 'Cry', category: 'Faces' },
  { id: 'face_75', emoji: '😭', name: 'Sob', category: 'Faces' },
  { id: 'face_76', emoji: '😱', name: 'Scream', category: 'Faces' },
  { id: 'face_77', emoji: '😖', name: 'Confounded', category: 'Faces' },
  { id: 'face_78', emoji: '😣', name: 'Persevere', category: 'Faces' },
  { id: 'face_79', emoji: '😞', name: 'Disappointed', category: 'Faces' },
  { id: 'face_80', emoji: '😓', name: 'Downcast', category: 'Faces' },
  { id: 'face_81', emoji: '😩', name: 'Weary', category: 'Faces' },
  { id: 'face_82', emoji: '😫', name: 'Tired', category: 'Faces' },
  { id: 'face_83', emoji: '🥱', name: 'Yawn', category: 'Faces' },
  { id: 'face_84', emoji: '😤', name: 'Triumph', category: 'Faces' },
  { id: 'face_85', emoji: '😡', name: 'Angry', category: 'Faces' },
  { id: 'face_86', emoji: '😠', name: 'Mad', category: 'Faces' },
  { id: 'face_87', emoji: '🤬', name: 'Cursing', category: 'Faces' },
  { id: 'face_88', emoji: '😈', name: 'Devil', category: 'Faces' },
  { id: 'face_89', emoji: '👿', name: 'Imp', category: 'Faces' },
  { id: 'face_90', emoji: '💀', name: 'Skull', category: 'Faces' },
  { id: 'face_91', emoji: '☠️', name: 'Crossbones', category: 'Faces' },
  { id: 'face_92', emoji: '💩', name: 'Poop', category: 'Faces' },
  { id: 'face_93', emoji: '🤡', name: 'Clown', category: 'Faces' },
  { id: 'face_94', emoji: '👹', name: 'Ogre', category: 'Faces' },
  { id: 'face_95', emoji: '👺', name: 'Goblin', category: 'Faces' },
  { id: 'face_96', emoji: '👻', name: 'Ghost', category: 'Faces' },
  { id: 'face_97', emoji: '👽', name: 'Alien', category: 'Faces' },
  { id: 'face_98', emoji: '👾', name: 'Space Invader', category: 'Faces' },
  { id: 'face_99', emoji: '🤖', name: 'Robot', category: 'Faces' },

  // Gestures & Hands
  { id: 'gest_1', emoji: '👋', name: 'Wave', category: 'Gestures' },
  { id: 'gest_2', emoji: '🤚', name: 'Raised Back', category: 'Gestures' },
  { id: 'gest_3', emoji: '🖐️', name: 'Hand Splayed', category: 'Gestures' },
  { id: 'gest_4', emoji: '✋', name: 'Raised Hand', category: 'Gestures' },
  { id: 'gest_5', emoji: '🖖', name: 'Vulcan', category: 'Gestures' },
  { id: 'gest_6', emoji: '👌', name: 'OK', category: 'Gestures' },
  { id: 'gest_7', emoji: '🤌', name: 'Pinched', category: 'Gestures' },
  { id: 'gest_8', emoji: '🤏', name: 'Pinching', category: 'Gestures' },
  { id: 'gest_9', emoji: '✌️', name: 'Peace', category: 'Gestures' },
  { id: 'gest_10', emoji: '🤞', name: 'Crossed', category: 'Gestures' },
  { id: 'gest_11', emoji: '🤟', name: 'Love You', category: 'Gestures' },
  { id: 'gest_12', emoji: '🤘', name: 'Rock On', category: 'Gestures' },
  { id: 'gest_13', emoji: '🤙', name: 'Call Me', category: 'Gestures' },
  { id: 'gest_14', emoji: '👈', name: 'Left', category: 'Gestures' },
  { id: 'gest_15', emoji: '👉', name: 'Right', category: 'Gestures' },
  { id: 'gest_16', emoji: '👆', name: 'Up', category: 'Gestures' },
  { id: 'gest_17', emoji: '👇', name: 'Down', category: 'Gestures' },
  { id: 'gest_18', emoji: '☝️', name: 'Index Up', category: 'Gestures' },
  { id: 'gest_19', emoji: '👍', name: 'Thumbs Up', category: 'Gestures' },
  { id: 'gest_20', emoji: '👎', name: 'Thumbs Down', category: 'Gestures' },
  { id: 'gest_21', emoji: '✊', name: 'Fist', category: 'Gestures' },
  { id: 'gest_22', emoji: '👊', name: 'Fist Bump', category: 'Gestures' },
  { id: 'gest_23', emoji: '🤛', name: 'Left Fist', category: 'Gestures' },
  { id: 'gest_24', emoji: '🤜', name: 'Right Fist', category: 'Gestures' },
  { id: 'gest_25', emoji: '👏', name: 'Clap', category: 'Gestures' },
  { id: 'gest_26', emoji: '🙌', name: 'Raising Hands', category: 'Gestures' },
  { id: 'gest_27', emoji: '👐', name: 'Open Hands', category: 'Gestures' },
  { id: 'gest_28', emoji: '🤲', name: 'Palms Together', category: 'Gestures' },
  { id: 'gest_29', emoji: '🤝', name: 'Handshake', category: 'Gestures' },
  { id: 'gest_30', emoji: '🙏', name: 'Pray', category: 'Gestures' },
  { id: 'gest_31', emoji: '✍️', name: 'Writing', category: 'Gestures' },
  { id: 'gest_32', emoji: '💪', name: 'Muscle', category: 'Gestures' },
  { id: 'gest_33', emoji: '🦾', name: 'Mechanical Arm', category: 'Gestures' },
  { id: 'gest_34', emoji: '🦵', name: 'Leg', category: 'Gestures' },
  { id: 'gest_35', emoji: '🦿', name: 'Mechanical Leg', category: 'Gestures' },

  // Animals & Nature
  { id: 'anim_1', emoji: '🐶', name: 'Dog', category: 'Animals' },
  { id: 'anim_2', emoji: '🐱', name: 'Cat', category: 'Animals' },
  { id: 'anim_3', emoji: '🐭', name: 'Mouse', category: 'Animals' },
  { id: 'anim_4', emoji: '🐹', name: 'Hamster', category: 'Animals' },
  { id: 'anim_5', emoji: '🐰', name: 'Rabbit', category: 'Animals' },
  { id: 'anim_6', emoji: '🦊', name: 'Fox', category: 'Animals' },
  { id: 'anim_7', emoji: '🐻', name: 'Bear', category: 'Animals' },
  { id: 'anim_8', emoji: '🐼', name: 'Panda', category: 'Animals' },
  { id: 'anim_9', emoji: '🐨', name: 'Koala', category: 'Animals' },
  { id: 'anim_10', emoji: '🐯', name: 'Tiger', category: 'Animals' },
  { id: 'anim_11', emoji: '🦁', name: 'Lion', category: 'Animals' },
  { id: 'anim_12', emoji: '🐮', name: 'Cow', category: 'Animals' },
  { id: 'anim_13', emoji: '🐷', name: 'Pig', category: 'Animals' },
  { id: 'anim_14', emoji: '🐸', name: 'Frog', category: 'Animals' },
  { id: 'anim_15', emoji: '🐵', name: 'Monkey', category: 'Animals' },
  { id: 'anim_16', emoji: '🙈', name: 'See No Evil', category: 'Animals' },
  { id: 'anim_17', emoji: '🙉', name: 'Hear No Evil', category: 'Animals' },
  { id: 'anim_18', emoji: '🙊', name: 'Speak No Evil', category: 'Animals' },
  { id: 'anim_19', emoji: '🐔', name: 'Chicken', category: 'Animals' },
  { id: 'anim_20', emoji: '🐧', name: 'Penguin', category: 'Animals' },
  { id: 'anim_21', emoji: '🐦', name: 'Bird', category: 'Animals' },
  { id: 'anim_22', emoji: '🐤', name: 'Chick', category: 'Animals' },
  { id: 'anim_23', emoji: '🦆', name: 'Duck', category: 'Animals' },
  { id: 'anim_24', emoji: '🦅', name: 'Eagle', category: 'Animals' },
  { id: 'anim_25', emoji: '🦉', name: 'Owl', category: 'Animals' },
  { id: 'anim_26', emoji: '🦇', name: 'Bat', category: 'Animals' },
  { id: 'anim_27', emoji: '🐺', name: 'Wolf', category: 'Animals' },
  { id: 'anim_28', emoji: '🐗', name: 'Boar', category: 'Animals' },
  { id: 'anim_29', emoji: '🐴', name: 'Horse', category: 'Animals' },
  { id: 'anim_30', emoji: '🦄', name: 'Unicorn', category: 'Animals' },
  { id: 'anim_31', emoji: '🐝', name: 'Bee', category: 'Animals' },
  { id: 'anim_32', emoji: '🐛', name: 'Bug', category: 'Animals' },
  { id: 'anim_33', emoji: '🦋', name: 'Butterfly', category: 'Animals' },
  { id: 'anim_34', emoji: '🐌', name: 'Snail', category: 'Animals' },
  { id: 'anim_35', emoji: '🐞', name: 'Ladybug', category: 'Animals' },
  { id: 'anim_36', emoji: '🐢', name: 'Turtle', category: 'Animals' },
  { id: 'anim_37', emoji: '🐍', name: 'Snake', category: 'Animals' },
  { id: 'anim_38', emoji: '🦎', name: 'Lizard', category: 'Animals' },
  { id: 'anim_39', emoji: '🦖', name: 'T-Rex', category: 'Animals' },
  { id: 'anim_40', emoji: '🦕', name: 'Dinosaur', category: 'Animals' },
  { id: 'anim_41', emoji: '🐙', name: 'Octopus', category: 'Animals' },
  { id: 'anim_42', emoji: '🦑', name: 'Squid', category: 'Animals' },
  { id: 'anim_43', emoji: '🦐', name: 'Shrimp', category: 'Animals' },
  { id: 'anim_44', emoji: '🦀', name: 'Crab', category: 'Animals' },
  { id: 'anim_45', emoji: '🐡', name: 'Blowfish', category: 'Animals' },
  { id: 'anim_46', emoji: '🐠', name: 'Tropical Fish', category: 'Animals' },
  { id: 'anim_47', emoji: '🐟', name: 'Fish', category: 'Animals' },
  { id: 'anim_48', emoji: '🐬', name: 'Dolphin', category: 'Animals' },
  { id: 'anim_49', emoji: '🐳', name: 'Whale', category: 'Animals' },
  { id: 'anim_50', emoji: '🦈', name: 'Shark', category: 'Animals' },

  // Food & Drink
  { id: 'food_1', emoji: '🍔', name: 'Burger', category: 'Food' },
  { id: 'food_2', emoji: '🍕', name: 'Pizza', category: 'Food' },
  { id: 'food_3', emoji: '🌭', name: 'Hot Dog', category: 'Food' },
  { id: 'food_4', emoji: '🥪', name: 'Sandwich', category: 'Food' },
  { id: 'food_5', emoji: '🌮', name: 'Taco', category: 'Food' },
  { id: 'food_6', emoji: '🌯', name: 'Burrito', category: 'Food' },
  { id: 'food_7', emoji: '🍿', name: 'Popcorn', category: 'Food' },
  { id: 'food_8', emoji: '🧈', name: 'Butter', category: 'Food' },
  { id: 'food_9', emoji: '🥓', name: 'Bacon', category: 'Food' },
  { id: 'food_10', emoji: '🍗', name: 'Chicken Leg', category: 'Food' },
  { id: 'food_11', emoji: '🍖', name: 'Meat', category: 'Food' },
  { id: 'food_12', emoji: '🦴', name: 'Bone', category: 'Food' },
  { id: 'food_13', emoji: '🍟', name: 'Fries', category: 'Food' },
  { id: 'food_14', emoji: '🍕', name: 'Pizza Slice', category: 'Food' },
  { id: 'food_15', emoji: '🍝', name: 'Spaghetti', category: 'Food' },
  { id: 'food_16', emoji: '🍜', name: 'Ramen', category: 'Food' },
  { id: 'food_17', emoji: '🍲', name: 'Stew', category: 'Food' },
  { id: 'food_18', emoji: '🍛', name: 'Curry', category: 'Food' },
  { id: 'food_19', emoji: '🍣', name: 'Sushi', category: 'Food' },
  { id: 'food_20', emoji: '🍱', name: 'Bento', category: 'Food' },
  { id: 'food_21', emoji: '🥟', name: 'Dumpling', category: 'Food' },
  { id: 'food_22', emoji: '🦪', name: 'Oyster', category: 'Food' },
  { id: 'food_23', emoji: '🍤', name: 'Shrimp', category: 'Food' },
  { id: 'food_24', emoji: '🍙', name: 'Rice Ball', category: 'Food' },
  { id: 'food_25', emoji: '🍚', name: 'Rice', category: 'Food' },
  { id: 'food_26', emoji: '🍘', name: 'Cracker', category: 'Food' },
  { id: 'food_27', emoji: '🍥', name: 'Fish Cake', category: 'Food' },
  { id: 'food_28', emoji: '🥠', name: 'Fortune Cookie', category: 'Food' },
  { id: 'food_29', emoji: '🥮', name: 'Moon Cake', category: 'Food' },
  { id: 'food_30', emoji: '🍢', name: 'Oden', category: 'Food' },
  { id: 'food_31', emoji: '🍡', name: 'Dango', category: 'Food' },
  { id: 'food_32', emoji: '🍧', name: 'Shaved Ice', category: 'Food' },
  { id: 'food_33', emoji: '🍨', name: 'Ice Cream', category: 'Food' },
  { id: 'food_34', emoji: '🍦', name: 'Soft Ice Cream', category: 'Food' },
  { id: 'food_35', emoji: '🥧', name: 'Pie', category: 'Food' },
  { id: 'food_36', emoji: '🧁', name: 'Cupcake', category: 'Food' },
  { id: 'food_37', emoji: '🍰', name: 'Cake', category: 'Food' },
  { id: 'food_38', emoji: '🎂', name: 'Birthday Cake', category: 'Food' },
  { id: 'food_39', emoji: '🍮', name: 'Pudding', category: 'Food' },
  { id: 'food_40', emoji: '🍭', name: 'Lollipop', category: 'Food' },
  { id: 'food_41', emoji: '🍬', name: 'Candy', category: 'Food' },
  { id: 'food_42', emoji: '🍫', name: 'Chocolate', category: 'Food' },
  { id: 'food_43', emoji: '🍩', name: 'Donut', category: 'Food' },
  { id: 'food_44', emoji: '🍪', name: 'Cookie', category: 'Food' },
  { id: 'food_45', emoji: '🌰', name: 'Chestnut', category: 'Food' },
  { id: 'food_46', emoji: '🥜', name: 'Peanuts', category: 'Food' },
  { id: 'food_47', emoji: '🍯', name: 'Honey', category: 'Food' },
  { id: 'food_48', emoji: '🥛', name: 'Milk', category: 'Food' },
  { id: 'food_49', emoji: '🍼', name: 'Baby Bottle', category: 'Food' },
  { id: 'food_50', emoji: '☕', name: 'Coffee', category: 'Food' },

  // Activities & Sports
  { id: 'act_1', emoji: '⚽', name: 'Soccer', category: 'Activities' },
  { id: 'act_2', emoji: '🏀', name: 'Basketball', category: 'Activities' },
  { id: 'act_3', emoji: '🏈', name: 'Football', category: 'Activities' },
  { id: 'act_4', emoji: '⚾', name: 'Baseball', category: 'Activities' },
  { id: 'act_5', emoji: '🥎', name: 'Softball', category: 'Activities' },
  { id: 'act_6', emoji: '🎾', name: 'Tennis', category: 'Activities' },
  { id: 'act_7', emoji: '🏐', name: 'Volleyball', category: 'Activities' },
  { id: 'act_8', emoji: '🏉', name: 'Rugby', category: 'Activities' },
  { id: 'act_9', emoji: '🥏', name: 'Frisbee', category: 'Activities' },
  { id: 'act_10', emoji: '🎱', name: '8 Ball', category: 'Activities' },
  { id: 'act_11', emoji: '🪀', name: 'Yo-Yo', category: 'Activities' },
  { id: 'act_12', emoji: '🏓', name: 'Ping Pong', category: 'Activities' },
  { id: 'act_13', emoji: '🏸', name: 'Badminton', category: 'Activities' },
  { id: 'act_14', emoji: '🏒', name: 'Hockey', category: 'Activities' },
  { id: 'act_15', emoji: '🏑', name: 'Field Hockey', category: 'Activities' },
  { id: 'act_16', emoji: '🥍', name: 'Lacrosse', category: 'Activities' },
  { id: 'act_17', emoji: '🏏', name: 'Cricket', category: 'Activities' },
  { id: 'act_18', emoji: '🪃', name: 'Boomerang', category: 'Activities' },
  { id: 'act_19', emoji: '🥅', name: 'Goal', category: 'Activities' },
  { id: 'act_20', emoji: '⛳', name: 'Golf', category: 'Activities' },
  { id: 'act_21', emoji: '🏹', name: 'Archery', category: 'Activities' },
  { id: 'act_22', emoji: '🎣', name: 'Fishing', category: 'Activities' },
  { id: 'act_23', emoji: '🥊', name: 'Boxing', category: 'Activities' },
  { id: 'act_24', emoji: '🥋', name: 'Martial Arts', category: 'Activities' },
  { id: 'act_25', emoji: '🎮', name: 'Game', category: 'Activities' },
  { id: 'act_26', emoji: '🕹️', name: 'Joystick', category: 'Activities' },
  { id: 'act_27', emoji: '🎰', name: 'Slot Machine', category: 'Activities' },
  { id: 'act_28', emoji: '🎲', name: 'Dice', category: 'Activities' },
  { id: 'act_29', emoji: '🧩', name: 'Puzzle', category: 'Activities' },
  { id: 'act_30', emoji: '🎯', name: 'Bullseye', category: 'Activities' },

  // Objects & Symbols
  { id: 'obj_1', emoji: '❤️', name: 'Heart', category: 'Objects' },
  { id: 'obj_2', emoji: '🧡', name: 'Orange Heart', category: 'Objects' },
  { id: 'obj_3', emoji: '💛', name: 'Yellow Heart', category: 'Objects' },
  { id: 'obj_4', emoji: '💚', name: 'Green Heart', category: 'Objects' },
  { id: 'obj_5', emoji: '💙', name: 'Blue Heart', category: 'Objects' },
  { id: 'obj_6', emoji: '💜', name: 'Purple Heart', category: 'Objects' },
  { id: 'obj_7', emoji: '🖤', name: 'Black Heart', category: 'Objects' },
  { id: 'obj_8', emoji: '🤍', name: 'White Heart', category: 'Objects' },
  { id: 'obj_9', emoji: '🤎', name: 'Brown Heart', category: 'Objects' },
  { id: 'obj_10', emoji: '💔', name: 'Broken Heart', category: 'Objects' },
  { id: 'obj_11', emoji: '❣️', name: 'Heart Exclamation', category: 'Objects' },
  { id: 'obj_12', emoji: '💕', name: 'Two Hearts', category: 'Objects' },
  { id: 'obj_13', emoji: '💞', name: 'Revolving Hearts', category: 'Objects' },
  { id: 'obj_14', emoji: '💓', name: 'Beating Heart', category: 'Objects' },
  { id: 'obj_15', emoji: '💗', name: 'Growing Heart', category: 'Objects' },
  { id: 'obj_16', emoji: '💖', name: 'Sparkling Heart', category: 'Objects' },
  { id: 'obj_17', emoji: '💘', name: 'Cupid', category: 'Objects' },
  { id: 'obj_18', emoji: '💝', name: 'Gift Heart', category: 'Objects' },
  { id: 'obj_19', emoji: '💟', name: 'Heart Decoration', category: 'Objects' },
  { id: 'obj_20', emoji: '☮️', name: 'Peace', category: 'Objects' },
  { id: 'obj_21', emoji: '✝️', name: 'Cross', category: 'Objects' },
  { id: 'obj_22', emoji: '☪️', name: 'Star Crescent', category: 'Objects' },
  { id: 'obj_23', emoji: '🕉️', name: 'Om', category: 'Objects' },
  { id: 'obj_24', emoji: '☸️', name: 'Wheel of Dharma', category: 'Objects' },
  { id: 'obj_25', emoji: '✡️', name: 'Star of David', category: 'Objects' },
  { id: 'obj_26', emoji: '🔯', name: 'Dotted Six', category: 'Objects' },
  { id: 'obj_27', emoji: '🕎', name: 'Menorah', category: 'Objects' },
  { id: 'obj_28', emoji: '☯️', name: 'Yin Yang', category: 'Objects' },
  { id: 'obj_29', emoji: '☦️', name: 'Orthodox Cross', category: 'Objects' },
  { id: 'obj_30', emoji: '🛐', name: 'Place of Worship', category: 'Objects' },

  // Symbols & Icons
  { id: 'sym_1', emoji: '⚠️', name: 'Warning', category: 'Symbols' },
  { id: 'sym_2', emoji: '🚫', name: 'Prohibited', category: 'Symbols' },
  { id: 'sym_3', emoji: '✅', name: 'Check Mark', category: 'Symbols' },
  { id: 'sym_4', emoji: '❌', name: 'X', category: 'Symbols' },
  { id: 'sym_5', emoji: '⭕', name: 'Circle', category: 'Symbols' },
  { id: 'sym_6', emoji: '❓', name: 'Question', category: 'Symbols' },
  { id: 'sym_7', emoji: '❗', name: 'Exclamation', category: 'Symbols' },
  { id: 'sym_8', emoji: '💯', name: '100', category: 'Symbols' },
  { id: 'sym_9', emoji: '🔥', name: 'Fire', category: 'Symbols' },
  { id: 'sym_10', emoji: '⭐', name: 'Star', category: 'Symbols' },
  { id: 'sym_11', emoji: '✨', name: 'Sparkles', category: 'Symbols' },
  { id: 'sym_12', emoji: '💫', name: 'Dizzy', category: 'Symbols' },
  { id: 'sym_13', emoji: '💥', name: 'Boom', category: 'Symbols' },
  { id: 'sym_14', emoji: '💢', name: 'Anger', category: 'Symbols' },
  { id: 'sym_15', emoji: '💦', name: 'Sweat Droplets', category: 'Symbols' },
  { id: 'sym_16', emoji: '💨', name: 'Dash', category: 'Symbols' },
  { id: 'sym_17', emoji: '🕳️', name: 'Hole', category: 'Symbols' },
  { id: 'sym_18', emoji: '💬', name: 'Speech Balloon', category: 'Symbols' },
  { id: 'sym_19', emoji: '👁️‍🗨️', name: 'Eye Speech', category: 'Symbols' },
  { id: 'sym_20', emoji: '🗨️', name: 'Left Speech', category: 'Symbols' },
  { id: 'sym_21', emoji: '🗯️', name: 'Right Anger', category: 'Symbols' },
  { id: 'sym_22', emoji: '💭', name: 'Thought Balloon', category: 'Symbols' },
  { id: 'sym_23', emoji: '💤', name: 'Zzz', category: 'Symbols' },
  { id: 'sym_24', emoji: '🔔', name: 'Bell', category: 'Symbols' },
  { id: 'sym_25', emoji: '🔕', name: 'No Bell', category: 'Symbols' },
  { id: 'sym_26', emoji: '🎵', name: 'Music Note', category: 'Symbols' },
  { id: 'sym_27', emoji: '🎶', name: 'Music Notes', category: 'Symbols' },
  { id: 'sym_28', emoji: '💲', name: 'Dollar', category: 'Symbols' },
  { id: 'sym_29', emoji: '💰', name: 'Money Bag', category: 'Symbols' },
  { id: 'sym_30', emoji: '🏆', name: 'Trophy', category: 'Symbols' },
];

export const getStickersByCategory = (category: string): Sticker[] => {
  return stickers.filter(sticker => sticker.category === category);
};

export const searchStickers = (query: string): Sticker[] => {
  const lowerQuery = query.toLowerCase();
  return stickers.filter(sticker =>
    sticker.name.toLowerCase().includes(lowerQuery) ||
    sticker.emoji.includes(query)
  );
};
